name: plant_monitoring_system
description: A Flutter application for plant monitoring.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  fl_chart: ^0.63.0
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env